# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/ui/qtsixa_mainw.ui'
#
# Created: Sat Sep 17 22:26:06 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QtSixAMainW(object):
    def setupUi(self, QtSixAMainW):
        QtSixAMainW.setObjectName(_fromUtf8("QtSixAMainW"))
        QtSixAMainW.resize(710, 461)
        QtSixAMainW.setWindowTitle(QtGui.QApplication.translate("QtSixAMainW", "QtSixA", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(QtSixAMainW)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.devices = QtGui.QWidget()
        self.devices.setObjectName(_fromUtf8("devices"))
        self.gridLayout_5 = QtGui.QGridLayout(self.devices)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_2 = QtGui.QFrame(self.devices)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("QtSixAMainW", "Welcome to QtSixA!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout_5.addWidget(self.frame_2, 0, 0, 1, 1)
        self.groupDevice = QtGui.QGroupBox(self.devices)
        self.groupDevice.setTitle(QtGui.QApplication.translate("QtSixAMainW", "Device Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.groupDevice.setObjectName(_fromUtf8("groupDevice"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupDevice)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.groupDevice)
        self.label_7.setText(QtGui.QApplication.translate("QtSixAMainW", "&Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineName = QtGui.QLineEdit(self.groupDevice)
        self.lineName.setEnabled(True)
        self.lineName.setAcceptDrops(False)
        self.lineName.setText(_fromUtf8("_DEV_NAME_"))
        self.lineName.setReadOnly(True)
        self.lineName.setObjectName(_fromUtf8("lineName"))
        self.gridLayout_3.addWidget(self.lineName, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupDevice)
        self.label_8.setText(QtGui.QApplication.translate("QtSixAMainW", "&Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineType = QtGui.QLineEdit(self.groupDevice)
        self.lineType.setEnabled(True)
        self.lineType.setAcceptDrops(False)
        self.lineType.setText(QtGui.QApplication.translate("QtSixAMainW", "_DEV_TYPE_", None, QtGui.QApplication.UnicodeUTF8))
        self.lineType.setReadOnly(True)
        self.lineType.setObjectName(_fromUtf8("lineType"))
        self.gridLayout_3.addWidget(self.lineType, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupDevice)
        self.label_11.setText(_fromUtf8("&ID:"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.lineID = QtGui.QLineEdit(self.groupDevice)
        self.lineID.setEnabled(True)
        self.lineID.setAcceptDrops(False)
        self.lineID.setText(_fromUtf8("_DEV_ID_"))
        self.lineID.setReadOnly(True)
        self.lineID.setObjectName(_fromUtf8("lineID"))
        self.gridLayout_3.addWidget(self.lineID, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupDevice)
        self.label_9.setText(QtGui.QApplication.translate("QtSixAMainW", "&Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.lineMode = QtGui.QLineEdit(self.groupDevice)
        self.lineMode.setEnabled(True)
        self.lineMode.setAcceptDrops(False)
        self.lineMode.setText(_fromUtf8("_DEV_MODE_"))
        self.lineMode.setReadOnly(True)
        self.lineMode.setObjectName(_fromUtf8("lineMode"))
        self.gridLayout_3.addWidget(self.lineMode, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupDevice, 0, 1, 2, 1)
        self.listOfDevices = QtGui.QListWidget(self.devices)
        self.listOfDevices.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listOfDevices.setObjectName(_fromUtf8("listOfDevices"))
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("QtSixAMainW", "(no devices found)", None, QtGui.QApplication.UnicodeUTF8))
        self.listOfDevices.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(_fromUtf8("BT_1"))
        self.listOfDevices.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(_fromUtf8("BT_2"))
        self.listOfDevices.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(_fromUtf8("BT_3"))
        self.listOfDevices.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(_fromUtf8("BT_4"))
        self.listOfDevices.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(_fromUtf8("BT_5"))
        self.listOfDevices.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(_fromUtf8("BT_6"))
        self.listOfDevices.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(_fromUtf8("BT_7"))
        self.listOfDevices.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(_fromUtf8("BT_8"))
        self.listOfDevices.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(_fromUtf8("USB_1"))
        self.listOfDevices.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(_fromUtf8("USB_2"))
        self.listOfDevices.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(_fromUtf8("USB_3"))
        self.listOfDevices.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(_fromUtf8("USB_4"))
        self.listOfDevices.addItem(item)
        self.gridLayout_5.addWidget(self.listOfDevices, 1, 0, 2, 1)
        self.groupBluetooth = QtGui.QGroupBox(self.devices)
        self.groupBluetooth.setTitle(QtGui.QApplication.translate("QtSixAMainW", "Bluetooth Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBluetooth.setObjectName(_fromUtf8("groupBluetooth"))
        self.gridLayout = QtGui.QGridLayout(self.groupBluetooth)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_10 = QtGui.QLabel(self.groupBluetooth)
        self.label_10.setText(QtGui.QApplication.translate("QtSixAMainW", "&Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineAddress = QtGui.QLineEdit(self.groupBluetooth)
        self.lineAddress.setEnabled(True)
        self.lineAddress.setAcceptDrops(False)
        self.lineAddress.setText(_fromUtf8("XX:XX:XX:XX"))
        self.lineAddress.setReadOnly(True)
        self.lineAddress.setObjectName(_fromUtf8("lineAddress"))
        self.gridLayout.addWidget(self.lineAddress, 0, 1, 1, 1)
        self.label_LQ = QtGui.QLabel(self.groupBluetooth)
        self.label_LQ.setEnabled(True)
        self.label_LQ.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Signal quality of the selected device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_LQ.setText(QtGui.QApplication.translate("QtSixAMainW", "Signal quality:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_LQ.setObjectName(_fromUtf8("label_LQ"))
        self.gridLayout.addWidget(self.label_LQ, 1, 0, 1, 1)
        self.barLQ = QtGui.QProgressBar(self.groupBluetooth)
        self.barLQ.setEnabled(True)
        self.barLQ.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Signal quality of the selected device", None, QtGui.QApplication.UnicodeUTF8))
        self.barLQ.setMaximum(255)
        self.barLQ.setProperty("value", 0)
        self.barLQ.setFormat(_fromUtf8("%p%"))
        self.barLQ.setObjectName(_fromUtf8("barLQ"))
        self.gridLayout.addWidget(self.barLQ, 1, 1, 1, 1)
        self.label_bat = QtGui.QLabel(self.groupBluetooth)
        self.label_bat.setEnabled(True)
        self.label_bat.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Battery charge status of the selected Sixaxis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bat.setText(QtGui.QApplication.translate("QtSixAMainW", "Battery status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bat.setObjectName(_fromUtf8("label_bat"))
        self.gridLayout.addWidget(self.label_bat, 2, 0, 1, 1)
        self.barBattery = QtGui.QProgressBar(self.groupBluetooth)
        self.barBattery.setEnabled(True)
        self.barBattery.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Battery charge status of the selected Sixaxis", None, QtGui.QApplication.UnicodeUTF8))
        self.barBattery.setMaximum(5)
        self.barBattery.setProperty("value", 0)
        self.barBattery.setFormat(_fromUtf8("%v/5"))
        self.barBattery.setObjectName(_fromUtf8("barBattery"))
        self.gridLayout.addWidget(self.barBattery, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBluetooth)
        self.label_3.setText(QtGui.QApplication.translate("QtSixAMainW", "&Last time used:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineDate = QtGui.QLineEdit(self.groupBluetooth)
        self.lineDate.setReadOnly(True)
        self.lineDate.setObjectName(_fromUtf8("lineDate"))
        self.gridLayout.addWidget(self.lineDate, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBluetooth, 2, 1, 2, 1)
        self.groupActions = QtGui.QGroupBox(self.devices)
        self.groupActions.setTitle(QtGui.QApplication.translate("QtSixAMainW", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.groupActions.setAlignment(QtCore.Qt.AlignCenter)
        self.groupActions.setObjectName(_fromUtf8("groupActions"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupActions)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.b_disconnect = QtGui.QPushButton(self.groupActions)
        self.b_disconnect.setEnabled(True)
        self.b_disconnect.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Disconnect the selected device", None, QtGui.QApplication.UnicodeUTF8))
        self.b_disconnect.setText(QtGui.QApplication.translate("QtSixAMainW", "&Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/eject.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_disconnect.setIcon(icon)
        self.b_disconnect.setObjectName(_fromUtf8("b_disconnect"))
        self.gridLayout_2.addWidget(self.b_disconnect, 1, 0, 1, 1)
        self.b_battery = QtGui.QPushButton(self.groupActions)
        self.b_battery.setEnabled(True)
        self.b_battery.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "(Re)-Check the battery charge status of the selected Sixaxis", None, QtGui.QApplication.UnicodeUTF8))
        self.b_battery.setText(QtGui.QApplication.translate("QtSixAMainW", "Re-Check &Battery", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/battery.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_battery.setIcon(icon1)
        self.b_battery.setObjectName(_fromUtf8("b_battery"))
        self.gridLayout_2.addWidget(self.b_battery, 1, 2, 1, 1)
        self.b_disconnect_all = QtGui.QPushButton(self.groupActions)
        self.b_disconnect_all.setEnabled(True)
        self.b_disconnect_all.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Disconnect the selected device", None, QtGui.QApplication.UnicodeUTF8))
        self.b_disconnect_all.setText(QtGui.QApplication.translate("QtSixAMainW", "Disconnect &All", None, QtGui.QApplication.UnicodeUTF8))
        self.b_disconnect_all.setIcon(icon)
        self.b_disconnect_all.setObjectName(_fromUtf8("b_disconnect_all"))
        self.gridLayout_2.addWidget(self.b_disconnect_all, 2, 0, 1, 1)
        self.b_rumble = QtGui.QPushButton(self.groupActions)
        self.b_rumble.setText(QtGui.QApplication.translate("QtSixAMainW", "Test &Rumble", None, QtGui.QApplication.UnicodeUTF8))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/bug.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_rumble.setIcon(icon2)
        self.b_rumble.setObjectName(_fromUtf8("b_rumble"))
        self.gridLayout_2.addWidget(self.b_rumble, 2, 2, 1, 1)
        self.line = QtGui.QFrame(self.groupActions)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 0, 1, 3, 1)
        self.label_4 = QtGui.QLabel(self.groupActions)
        self.label_4.setText(QtGui.QApplication.translate("QtSixAMainW", "All Devices:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupActions)
        self.label_5.setText(QtGui.QApplication.translate("QtSixAMainW", "Sixaxis Only:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupActions, 3, 0, 2, 1)
        self.groupProfile = QtGui.QGroupBox(self.devices)
        self.groupProfile.setTitle(QtGui.QApplication.translate("QtSixAMainW", "Profile Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.groupProfile.setObjectName(_fromUtf8("groupProfile"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupProfile)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineProfile = QtGui.QLineEdit(self.groupProfile)
        self.lineProfile.setText(_fromUtf8(""))
        self.lineProfile.setReadOnly(True)
        self.lineProfile.setObjectName(_fromUtf8("lineProfile"))
        self.horizontalLayout_3.addWidget(self.lineProfile)
        self.gridLayout_5.addWidget(self.groupProfile, 4, 1, 1, 1)
        self.tabWidget.addTab(self.devices, _fromUtf8(""))
        self.game_profiles = QtGui.QWidget()
        self.game_profiles.setObjectName(_fromUtf8("game_profiles"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.game_profiles)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_games = QtGui.QLabel(self.game_profiles)
        self.label_games.setEnabled(True)
        self.label_games.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "It\'s a lazy way, you know...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_games.setText(QtGui.QApplication.translate("QtSixAMainW", "Instead of using a Sixaxis profile, you can edit the configuration files of a game to make it playable with a Sixaxis/DualShock3.\n"
"The profiles in this page are meant for that.\n"
"When you click to apply a profile here, the game\'s joystick configuration is modified.\n"
"This way you won\'t need to apply a Sixaxis profile to play that game with it.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_games.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_games.setWordWrap(True)
        self.label_games.setObjectName(_fromUtf8("label_games"))
        self.verticalLayout_3.addWidget(self.label_games)
        self.listOfGames = QtGui.QComboBox(self.game_profiles)
        self.listOfGames.setObjectName(_fromUtf8("listOfGames"))
        self.listOfGames.addItem(_fromUtf8(""))
        self.listOfGames.setItemText(0, _fromUtf8("ePSXe (Wine)"))
        self.listOfGames.addItem(_fromUtf8(""))
        self.listOfGames.setItemText(1, _fromUtf8("Extreme Tux Racer"))
        self.listOfGames.addItem(_fromUtf8(""))
        self.listOfGames.setItemText(2, _fromUtf8("Neverball / Neverputt"))
        self.listOfGames.addItem(_fromUtf8(""))
        self.listOfGames.setItemText(3, _fromUtf8("Super Tux Kart"))
        self.verticalLayout_3.addWidget(self.listOfGames)
        self.frame = QtGui.QFrame(self.game_profiles)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.wET = QtGui.QWidget(self.frame)
        self.wET.setObjectName(_fromUtf8("wET"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.wET)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.radio_etracer_axis = QtGui.QRadioButton(self.wET)
        self.radio_etracer_axis.setText(QtGui.QApplication.translate("QtSixAMainW", "All Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_etracer_axis.setObjectName(_fromUtf8("radio_etracer_axis"))
        self.verticalLayout_8.addWidget(self.radio_etracer_axis)
        self.radio_etracer_accel = QtGui.QRadioButton(self.wET)
        self.radio_etracer_accel.setText(QtGui.QApplication.translate("QtSixAMainW", "Accelerometer direction", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_etracer_accel.setObjectName(_fromUtf8("radio_etracer_accel"))
        self.verticalLayout_8.addWidget(self.radio_etracer_accel)
        self.radio_etracer_full = QtGui.QRadioButton(self.wET)
        self.radio_etracer_full.setText(QtGui.QApplication.translate("QtSixAMainW", "All Accelerometers", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_etracer_full.setObjectName(_fromUtf8("radio_etracer_full"))
        self.verticalLayout_8.addWidget(self.radio_etracer_full)
        self.gridLayout_4.addWidget(self.wET, 0, 1, 1, 1)
        self.wEP = QtGui.QWidget(self.frame)
        self.wEP.setObjectName(_fromUtf8("wEP"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.wEP)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.radio_game_epsxe_1 = QtGui.QRadioButton(self.wEP)
        self.radio_game_epsxe_1.setText(QtGui.QApplication.translate("QtSixAMainW", "1:1 PlayStation controller", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_game_epsxe_1.setObjectName(_fromUtf8("radio_game_epsxe_1"))
        self.verticalLayout_5.addWidget(self.radio_game_epsxe_1)
        self.radio_game_epsxe_axis = QtGui.QRadioButton(self.wEP)
        self.radio_game_epsxe_axis.setText(QtGui.QApplication.translate("QtSixAMainW", "Left axis as accelerometers", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_game_epsxe_axis.setObjectName(_fromUtf8("radio_game_epsxe_axis"))
        self.verticalLayout_5.addWidget(self.radio_game_epsxe_axis)
        self.radio_game_epsxe_drv = QtGui.QRadioButton(self.wEP)
        self.radio_game_epsxe_drv.setText(QtGui.QApplication.translate("QtSixAMainW", "Accelerometers for driving", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_game_epsxe_drv.setObjectName(_fromUtf8("radio_game_epsxe_drv"))
        self.verticalLayout_5.addWidget(self.radio_game_epsxe_drv)
        self.gridLayout_4.addWidget(self.wEP, 0, 0, 1, 1)
        self.wNE = QtGui.QWidget(self.frame)
        self.wNE.setObjectName(_fromUtf8("wNE"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.wNE)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.radio_neverball_axis = QtGui.QRadioButton(self.wNE)
        self.radio_neverball_axis.setText(QtGui.QApplication.translate("QtSixAMainW", "Left axis moves table", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_neverball_axis.setObjectName(_fromUtf8("radio_neverball_axis"))
        self.verticalLayout_12.addWidget(self.radio_neverball_axis)
        self.radio_neverball_accel = QtGui.QRadioButton(self.wNE)
        self.radio_neverball_accel.setText(QtGui.QApplication.translate("QtSixAMainW", "Accelerometers moves table", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_neverball_accel.setObjectName(_fromUtf8("radio_neverball_accel"))
        self.verticalLayout_12.addWidget(self.radio_neverball_accel)
        self.gridLayout_4.addWidget(self.wNE, 1, 0, 1, 1)
        self.wSTK = QtGui.QWidget(self.frame)
        self.wSTK.setObjectName(_fromUtf8("wSTK"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.wSTK)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.radio_stk_digital = QtGui.QRadioButton(self.wSTK)
        self.radio_stk_digital.setText(QtGui.QApplication.translate("QtSixAMainW", "All Digital", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_stk_digital.setObjectName(_fromUtf8("radio_stk_digital"))
        self.verticalLayout_14.addWidget(self.radio_stk_digital)
        self.radio_stk_axis = QtGui.QRadioButton(self.wSTK)
        self.radio_stk_axis.setText(QtGui.QApplication.translate("QtSixAMainW", "All Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_stk_axis.setObjectName(_fromUtf8("radio_stk_axis"))
        self.verticalLayout_14.addWidget(self.radio_stk_axis)
        self.radio_stk_accel = QtGui.QRadioButton(self.wSTK)
        self.radio_stk_accel.setText(QtGui.QApplication.translate("QtSixAMainW", "Accelerometer direction", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_stk_accel.setObjectName(_fromUtf8("radio_stk_accel"))
        self.verticalLayout_14.addWidget(self.radio_stk_accel)
        self.radio_stk_full = QtGui.QRadioButton(self.wSTK)
        self.radio_stk_full.setText(QtGui.QApplication.translate("QtSixAMainW", "All Accelerometers", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_stk_full.setObjectName(_fromUtf8("radio_stk_full"))
        self.verticalLayout_14.addWidget(self.radio_stk_full)
        self.gridLayout_4.addWidget(self.wSTK, 1, 1, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.b_game_help = QtGui.QPushButton(self.game_profiles)
        self.b_game_help.setText(QtGui.QApplication.translate("QtSixAMainW", "Help", None, QtGui.QApplication.UnicodeUTF8))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/manual.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_game_help.setIcon(icon3)
        self.b_game_help.setObjectName(_fromUtf8("b_game_help"))
        self.horizontalLayout_11.addWidget(self.b_game_help)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.b_game_apply = QtGui.QPushButton(self.game_profiles)
        self.b_game_apply.setEnabled(True)
        self.b_game_apply.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Enjoy!", None, QtGui.QApplication.UnicodeUTF8))
        self.b_game_apply.setText(QtGui.QApplication.translate("QtSixAMainW", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/apply.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_game_apply.setIcon(icon4)
        self.b_game_apply.setObjectName(_fromUtf8("b_game_apply"))
        self.horizontalLayout_11.addWidget(self.b_game_apply)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.game_profiles, _fromUtf8(""))
        self.advanced = QtGui.QWidget()
        self.advanced.setObjectName(_fromUtf8("advanced"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.advanced)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.advanced)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("QtSixAMainW", "Signal quality actions", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_signal_device = QtGui.QLabel(self.groupBox_3)
        self.label_signal_device.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "First, choose a device (must be bluetooth of course)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_signal_device.setText(QtGui.QApplication.translate("QtSixAMainW", "For this device:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_signal_device.setObjectName(_fromUtf8("label_signal_device"))
        self.horizontalLayout_20.addWidget(self.label_signal_device)
        self.combo_signal_device = QtGui.QComboBox(self.groupBox_3)
        self.combo_signal_device.setEnabled(False)
        self.combo_signal_device.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "First, choose a device (must be bluetooth of course)", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_signal_device.setObjectName(_fromUtf8("combo_signal_device"))
        self.combo_signal_device.addItem(_fromUtf8(""))
        self.combo_signal_device.setItemText(0, QtGui.QApplication.translate("QtSixAMainW", "(Press Refresh)", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_20.addWidget(self.combo_signal_device)
        self.verticalLayout_10.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_signal_operation = QtGui.QLabel(self.groupBox_3)
        self.label_signal_operation.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Then, a trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_signal_operation.setText(QtGui.QApplication.translate("QtSixAMainW", "When signal is:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_signal_operation.setObjectName(_fromUtf8("label_signal_operation"))
        self.horizontalLayout_16.addWidget(self.label_signal_operation)
        self.combo_signal_operation = QtGui.QComboBox(self.groupBox_3)
        self.combo_signal_operation.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Then, a trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_signal_operation.setObjectName(_fromUtf8("combo_signal_operation"))
        self.combo_signal_operation.addItem(_fromUtf8(""))
        self.combo_signal_operation.setItemText(0, QtGui.QApplication.translate("QtSixAMainW", "lower", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_signal_operation.addItem(_fromUtf8(""))
        self.combo_signal_operation.setItemText(1, QtGui.QApplication.translate("QtSixAMainW", "higher", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_signal_operation.addItem(_fromUtf8(""))
        self.combo_signal_operation.setItemText(2, QtGui.QApplication.translate("QtSixAMainW", "equal", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_16.addWidget(self.combo_signal_operation)
        self.label_signal_spi = QtGui.QLabel(self.groupBox_3)
        self.label_signal_spi.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Maybe you should check on the main tab for this..?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_signal_spi.setText(QtGui.QApplication.translate("QtSixAMainW", "than:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_signal_spi.setObjectName(_fromUtf8("label_signal_spi"))
        self.horizontalLayout_16.addWidget(self.label_signal_spi)
        self.spin_signal = QtGui.QSpinBox(self.groupBox_3)
        self.spin_signal.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Maybe you should check on the main tab for this..?", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_signal.setWrapping(False)
        self.spin_signal.setMaximum(100)
        self.spin_signal.setProperty("value", 50)
        self.spin_signal.setObjectName(_fromUtf8("spin_signal"))
        self.horizontalLayout_16.addWidget(self.spin_signal)
        self.label_signal_p = QtGui.QLabel(self.groupBox_3)
        self.label_signal_p.setStatusTip(_fromUtf8(""))
        self.label_signal_p.setText(_fromUtf8("%:"))
        self.label_signal_p.setObjectName(_fromUtf8("label_signal_p"))
        self.horizontalLayout_16.addWidget(self.label_signal_p)
        self.line_7 = QtGui.QFrame(self.groupBox_3)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_16.addWidget(self.line_7)
        self.box_signal_disc = QtGui.QCheckBox(self.groupBox_3)
        self.box_signal_disc.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Perform action also when the device is disconnected (otherwise the action cancels itself)", None, QtGui.QApplication.UnicodeUTF8))
        self.box_signal_disc.setText(QtGui.QApplication.translate("QtSixAMainW", "Disconnect also triggers action", None, QtGui.QApplication.UnicodeUTF8))
        self.box_signal_disc.setObjectName(_fromUtf8("box_signal_disc"))
        self.horizontalLayout_16.addWidget(self.box_signal_disc)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_signal_line = QtGui.QLabel(self.groupBox_3)
        self.label_signal_line.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "How good do you Linux?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_signal_line.setText(QtGui.QApplication.translate("QtSixAMainW", "Perform this bash/shell command:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_signal_line.setObjectName(_fromUtf8("label_signal_line"))
        self.horizontalLayout_21.addWidget(self.label_signal_line)
        self.line_signal_bash = QtGui.QLineEdit(self.groupBox_3)
        self.line_signal_bash.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "How good do you Linux?", None, QtGui.QApplication.UnicodeUTF8))
        self.line_signal_bash.setObjectName(_fromUtf8("line_signal_bash"))
        self.horizontalLayout_21.addWidget(self.line_signal_bash)
        self.b_tips_signal = QtGui.QPushButton(self.groupBox_3)
        self.b_tips_signal.setEnabled(False)
        self.b_tips_signal.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Need some tips?", None, QtGui.QApplication.UnicodeUTF8))
        self.b_tips_signal.setText(QtGui.QApplication.translate("QtSixAMainW", "Tips...", None, QtGui.QApplication.UnicodeUTF8))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/hint.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_tips_signal.setIcon(icon5)
        self.b_tips_signal.setObjectName(_fromUtf8("b_tips_signal"))
        self.horizontalLayout_21.addWidget(self.b_tips_signal)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.line_5 = QtGui.QFrame(self.groupBox_3)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_10.addWidget(self.line_5)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.b_reset_signal = QtGui.QPushButton(self.groupBox_3)
        self.b_reset_signal.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Reset/Remove all previous set-up actions", None, QtGui.QApplication.UnicodeUTF8))
        self.b_reset_signal.setText(QtGui.QApplication.translate("QtSixAMainW", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_reset_signal.setIcon(icon6)
        self.b_reset_signal.setObjectName(_fromUtf8("b_reset_signal"))
        self.horizontalLayout_22.addWidget(self.b_reset_signal)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem3)
        self.b_refresh_signal = QtGui.QPushButton(self.groupBox_3)
        self.b_refresh_signal.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Refresh the list of devices above", None, QtGui.QApplication.UnicodeUTF8))
        self.b_refresh_signal.setText(QtGui.QApplication.translate("QtSixAMainW", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_refresh_signal.setIcon(icon7)
        self.b_refresh_signal.setObjectName(_fromUtf8("b_refresh_signal"))
        self.horizontalLayout_22.addWidget(self.b_refresh_signal)
        self.b_apply_signal = QtGui.QPushButton(self.groupBox_3)
        self.b_apply_signal.setEnabled(False)
        self.b_apply_signal.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Don\'t forget you\'re running as root...", None, QtGui.QApplication.UnicodeUTF8))
        self.b_apply_signal.setText(QtGui.QApplication.translate("QtSixAMainW", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.b_apply_signal.setIcon(icon4)
        self.b_apply_signal.setObjectName(_fromUtf8("b_apply_signal"))
        self.horizontalLayout_22.addWidget(self.b_apply_signal)
        self.verticalLayout_10.addLayout(self.horizontalLayout_22)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.advanced)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("QtSixAMainW", "sixad driver on hidraw device", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setEnabled(False)
        self.label_17.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Use the sixad driver in a Sixaxis\' hidraw device (sixad-raw)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("QtSixAMainW", "You can connect Sixaxis through USB and apply the sixad driver to it.<br>\n"
"By watching \'dmesg\' you can know which hidraw device is from a Sixaxis.<br>\n"
"To start, just select the proper hidraw device and click apply.<br>\n"
"<i>\n"
"(Please note that you\'ll have to come here ayntime a new Sixaxis is connected)</i>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setWordWrap(False)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_7.addWidget(self.label_17)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_hidraw = QtGui.QLabel(self.groupBox_4)
        self.label_hidraw.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "List of hidraw devices", None, QtGui.QApplication.UnicodeUTF8))
        self.label_hidraw.setText(QtGui.QApplication.translate("QtSixAMainW", "Use this hidraw device:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_hidraw.setObjectName(_fromUtf8("label_hidraw"))
        self.horizontalLayout_26.addWidget(self.label_hidraw)
        self.combo_hidraw = QtGui.QComboBox(self.groupBox_4)
        self.combo_hidraw.setEnabled(False)
        self.combo_hidraw.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "List of hidraw devices", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_hidraw.setObjectName(_fromUtf8("combo_hidraw"))
        self.combo_hidraw.addItem(_fromUtf8(""))
        self.combo_hidraw.setItemText(0, QtGui.QApplication.translate("QtSixAMainW", "(Press Refresh)", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_26.addWidget(self.combo_hidraw)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.line_6 = QtGui.QFrame(self.groupBox_4)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_7.addWidget(self.line_6)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.b_stop_sixadraw = QtGui.QPushButton(self.groupBox_4)
        self.b_stop_sixadraw.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Stop sixad-raw (emergency button)", None, QtGui.QApplication.UnicodeUTF8))
        self.b_stop_sixadraw.setText(QtGui.QApplication.translate("QtSixAMainW", "Stop sixad-raw", None, QtGui.QApplication.UnicodeUTF8))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_stop_sixadraw.setIcon(icon8)
        self.b_stop_sixadraw.setObjectName(_fromUtf8("b_stop_sixadraw"))
        self.horizontalLayout_27.addWidget(self.b_stop_sixadraw)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem4)
        self.b_refresh_hidraw = QtGui.QPushButton(self.groupBox_4)
        self.b_refresh_hidraw.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Refresh the list of hidraw devices", None, QtGui.QApplication.UnicodeUTF8))
        self.b_refresh_hidraw.setText(QtGui.QApplication.translate("QtSixAMainW", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.b_refresh_hidraw.setIcon(icon7)
        self.b_refresh_hidraw.setObjectName(_fromUtf8("b_refresh_hidraw"))
        self.horizontalLayout_27.addWidget(self.b_refresh_hidraw)
        self.b_apply_hidraw = QtGui.QPushButton(self.groupBox_4)
        self.b_apply_hidraw.setEnabled(False)
        self.b_apply_hidraw.setStatusTip(QtGui.QApplication.translate("QtSixAMainW", "Start sixad-raw", None, QtGui.QApplication.UnicodeUTF8))
        self.b_apply_hidraw.setText(QtGui.QApplication.translate("QtSixAMainW", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.b_apply_hidraw.setIcon(icon4)
        self.b_apply_hidraw.setObjectName(_fromUtf8("b_apply_hidraw"))
        self.horizontalLayout_27.addWidget(self.b_apply_hidraw)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.advanced, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        QtSixAMainW.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(QtSixAMainW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setTitle(QtGui.QApplication.translate("QtSixAMainW", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menuWeb_Links = QtGui.QMenu(self.menu_Help)
        self.menuWeb_Links.setTitle(QtGui.QApplication.translate("QtSixAMainW", "&Web && Links", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWeb_Links.setObjectName(_fromUtf8("menuWeb_Links"))
        self.menu_Task = QtGui.QMenu(self.menubar)
        self.menu_Task.setTitle(QtGui.QApplication.translate("QtSixAMainW", "&Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Task.setObjectName(_fromUtf8("menu_Task"))
        self.menu_Disc = QtGui.QMenu(self.menu_Task)
        self.menu_Disc.setTitle(QtGui.QApplication.translate("QtSixAMainW", "&Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Disc.setObjectName(_fromUtf8("menu_Disc"))
        self.menu_Root = QtGui.QMenu(self.menu_Task)
        self.menu_Root.setTitle(QtGui.QApplication.translate("QtSixAMainW", "&Root Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Root.setObjectName(_fromUtf8("menu_Root"))
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setTitle(QtGui.QApplication.translate("QtSixAMainW", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Settings.setObjectName(_fromUtf8("menu_Settings"))
        self.menuAdvanced = QtGui.QMenu(self.menu_Settings)
        self.menuAdvanced.setTitle(QtGui.QApplication.translate("QtSixAMainW", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdvanced.setObjectName(_fromUtf8("menuAdvanced"))
        QtSixAMainW.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(QtSixAMainW)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        QtSixAMainW.setStatusBar(self.statusbar)
        self.act_DiscSixaxis = QtGui.QAction(QtSixAMainW)
        self.act_DiscSixaxis.setIcon(icon)
        self.act_DiscSixaxis.setText(QtGui.QApplication.translate("QtSixAMainW", "Disconnect All Sixaxis", None, QtGui.QApplication.UnicodeUTF8))
        self.act_DiscSixaxis.setObjectName(_fromUtf8("act_DiscSixaxis"))
        self.act_DiscDevices = QtGui.QAction(QtSixAMainW)
        self.act_DiscDevices.setIcon(icon)
        self.act_DiscDevices.setText(QtGui.QApplication.translate("QtSixAMainW", "Disconnect All Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.act_DiscDevices.setObjectName(_fromUtf8("act_DiscDevices"))
        self.act_none = QtGui.QAction(QtSixAMainW)
        self.act_none.setEnabled(False)
        self.act_none.setText(QtGui.QApplication.translate("QtSixAMainW", "(No device found)", None, QtGui.QApplication.UnicodeUTF8))
        self.act_none.setObjectName(_fromUtf8("act_none"))
        self.act_1 = QtGui.QAction(QtSixAMainW)
        self.act_1.setText(QtGui.QApplication.translate("QtSixAMainW", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.act_1.setObjectName(_fromUtf8("act_1"))
        self.act_2 = QtGui.QAction(QtSixAMainW)
        self.act_2.setText(QtGui.QApplication.translate("QtSixAMainW", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.act_2.setObjectName(_fromUtf8("act_2"))
        self.act_3 = QtGui.QAction(QtSixAMainW)
        self.act_3.setText(QtGui.QApplication.translate("QtSixAMainW", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.act_3.setObjectName(_fromUtf8("act_3"))
        self.act_4 = QtGui.QAction(QtSixAMainW)
        self.act_4.setText(QtGui.QApplication.translate("QtSixAMainW", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.act_4.setObjectName(_fromUtf8("act_4"))
        self.act_5 = QtGui.QAction(QtSixAMainW)
        self.act_5.setText(QtGui.QApplication.translate("QtSixAMainW", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.act_5.setObjectName(_fromUtf8("act_5"))
        self.act_6 = QtGui.QAction(QtSixAMainW)
        self.act_6.setText(QtGui.QApplication.translate("QtSixAMainW", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.act_6.setObjectName(_fromUtf8("act_6"))
        self.act_7 = QtGui.QAction(QtSixAMainW)
        self.act_7.setText(QtGui.QApplication.translate("QtSixAMainW", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.act_7.setObjectName(_fromUtf8("act_7"))
        self.act_8 = QtGui.QAction(QtSixAMainW)
        self.act_8.setText(QtGui.QApplication.translate("QtSixAMainW", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.act_8.setObjectName(_fromUtf8("act_8"))
        self.act_Pair = QtGui.QAction(QtSixAMainW)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/rec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_Pair.setIcon(icon9)
        self.act_Pair.setText(QtGui.QApplication.translate("QtSixAMainW", "&Pair Device to PC", None, QtGui.QApplication.UnicodeUTF8))
        self.act_Pair.setObjectName(_fromUtf8("act_Pair"))
        self.act_Configure = QtGui.QAction(QtSixAMainW)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_Configure.setIcon(icon10)
        self.act_Configure.setText(QtGui.QApplication.translate("QtSixAMainW", "&Configure QtSixA", None, QtGui.QApplication.UnicodeUTF8))
        self.act_Configure.setObjectName(_fromUtf8("act_Configure"))
        self.act_Manual = QtGui.QAction(QtSixAMainW)
        self.act_Manual.setIcon(icon3)
        self.act_Manual.setText(QtGui.QApplication.translate("QtSixAMainW", "&Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.act_Manual.setObjectName(_fromUtf8("act_Manual"))
        self.act_About = QtGui.QAction(QtSixAMainW)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/qtsixa_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_About.setIcon(icon11)
        self.act_About.setText(QtGui.QApplication.translate("QtSixAMainW", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.act_About.setObjectName(_fromUtf8("act_About"))
        self.act_WebPage = QtGui.QAction(QtSixAMainW)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/web.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_WebPage.setIcon(icon12)
        self.act_WebPage.setText(QtGui.QApplication.translate("QtSixAMainW", "QtSixA &WebPage", None, QtGui.QApplication.UnicodeUTF8))
        self.act_WebPage.setObjectName(_fromUtf8("act_WebPage"))
        self.act_Ubuntu = QtGui.QAction(QtSixAMainW)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/ubuntu.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_Ubuntu.setIcon(icon13)
        self.act_Ubuntu.setText(QtGui.QApplication.translate("QtSixAMainW", "&Ubuntu Forums", None, QtGui.QApplication.UnicodeUTF8))
        self.act_Ubuntu.setObjectName(_fromUtf8("act_Ubuntu"))
        self.act_Bug = QtGui.QAction(QtSixAMainW)
        self.act_Bug.setIcon(icon2)
        self.act_Bug.setText(QtGui.QApplication.translate("QtSixAMainW", "&Report a bug", None, QtGui.QApplication.UnicodeUTF8))
        self.act_Bug.setObjectName(_fromUtf8("act_Bug"))
        self.act_Donate = QtGui.QAction(QtSixAMainW)
        self.act_Donate.setText(QtGui.QApplication.translate("QtSixAMainW", "&Donate", None, QtGui.QApplication.UnicodeUTF8))
        self.act_Donate.setObjectName(_fromUtf8("act_Donate"))
        self.act_Exit = QtGui.QAction(QtSixAMainW)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_Exit.setIcon(icon14)
        self.act_Exit.setText(QtGui.QApplication.translate("QtSixAMainW", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.act_Exit.setObjectName(_fromUtf8("act_Exit"))
        self.act_bt_start = QtGui.QAction(QtSixAMainW)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/bt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_bt_start.setIcon(icon15)
        self.act_bt_start.setText(QtGui.QApplication.translate("QtSixAMainW", "&Start Bluetooth", None, QtGui.QApplication.UnicodeUTF8))
        self.act_bt_start.setObjectName(_fromUtf8("act_bt_start"))
        self.act_bt_stop = QtGui.QAction(QtSixAMainW)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/bt_off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_bt_stop.setIcon(icon16)
        self.act_bt_stop.setText(QtGui.QApplication.translate("QtSixAMainW", "S&top Bluetooth", None, QtGui.QApplication.UnicodeUTF8))
        self.act_bt_stop.setObjectName(_fromUtf8("act_bt_stop"))
        self.act_sixad_force = QtGui.QAction(QtSixAMainW)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/force.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_sixad_force.setIcon(icon17)
        self.act_sixad_force.setText(QtGui.QApplication.translate("QtSixAMainW", "&Force Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.act_sixad_force.setObjectName(_fromUtf8("act_sixad_force"))
        self.act_sixad_stop = QtGui.QAction(QtSixAMainW)
        self.act_sixad_stop.setIcon(icon8)
        self.act_sixad_stop.setText(QtGui.QApplication.translate("QtSixAMainW", "Stop si&xad", None, QtGui.QApplication.UnicodeUTF8))
        self.act_sixad_stop.setObjectName(_fromUtf8("act_sixad_stop"))
        self.act_Reference = QtGui.QAction(QtSixAMainW)
        self.act_Reference.setText(QtGui.QApplication.translate("QtSixAMainW", "Sixaxis &Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.act_Reference.setObjectName(_fromUtf8("act_Reference"))
        self.act_ManageProf = QtGui.QAction(QtSixAMainW)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/manage.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_ManageProf.setIcon(icon18)
        self.act_ManageProf.setText(QtGui.QApplication.translate("QtSixAMainW", "&Manage Devices/Profiles", None, QtGui.QApplication.UnicodeUTF8))
        self.act_ManageProf.setObjectName(_fromUtf8("act_ManageProf"))
        self.act_Debug = QtGui.QAction(QtSixAMainW)
        self.act_Debug.setText(QtGui.QApplication.translate("QtSixAMainW", "Configure Debug mode", None, QtGui.QApplication.UnicodeUTF8))
        self.act_Debug.setObjectName(_fromUtf8("act_Debug"))
        self.act_RestoreDef = QtGui.QAction(QtSixAMainW)
        self.act_RestoreDef.setIcon(icon6)
        self.act_RestoreDef.setText(QtGui.QApplication.translate("QtSixAMainW", "&Clear All QtSixA stuff", None, QtGui.QApplication.UnicodeUTF8))
        self.act_RestoreDef.setObjectName(_fromUtf8("act_RestoreDef"))
        self.menuWeb_Links.addAction(self.act_WebPage)
        self.menuWeb_Links.addAction(self.act_Ubuntu)
        self.menuWeb_Links.addSeparator()
        self.menuWeb_Links.addAction(self.act_Bug)
        self.menuWeb_Links.addAction(self.act_Donate)
        self.menu_Help.addAction(self.act_Manual)
        self.menu_Help.addAction(self.menuWeb_Links.menuAction())
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.act_Reference)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.act_About)
        self.menu_Disc.addAction(self.act_DiscSixaxis)
        self.menu_Disc.addAction(self.act_DiscDevices)
        self.menu_Disc.addSeparator()
        self.menu_Disc.addAction(self.act_none)
        self.menu_Disc.addAction(self.act_1)
        self.menu_Disc.addAction(self.act_2)
        self.menu_Disc.addAction(self.act_3)
        self.menu_Disc.addAction(self.act_4)
        self.menu_Disc.addAction(self.act_5)
        self.menu_Disc.addAction(self.act_6)
        self.menu_Disc.addAction(self.act_7)
        self.menu_Disc.addAction(self.act_8)
        self.menu_Root.addAction(self.act_bt_start)
        self.menu_Root.addAction(self.act_bt_stop)
        self.menu_Root.addSeparator()
        self.menu_Root.addAction(self.act_sixad_force)
        self.menu_Root.addAction(self.act_sixad_stop)
        self.menu_Task.addAction(self.menu_Disc.menuAction())
        self.menu_Task.addAction(self.act_Pair)
        self.menu_Task.addSeparator()
        self.menu_Task.addAction(self.menu_Root.menuAction())
        self.menu_Task.addSeparator()
        self.menu_Task.addAction(self.act_Exit)
        self.menuAdvanced.addAction(self.act_RestoreDef)
        self.menuAdvanced.addAction(self.act_Debug)
        self.menu_Settings.addAction(self.act_Configure)
        self.menu_Settings.addAction(self.act_ManageProf)
        self.menu_Settings.addSeparator()
        self.menu_Settings.addAction(self.menuAdvanced.menuAction())
        self.menubar.addAction(self.menu_Task.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.label_7.setBuddy(self.lineName)
        self.label_8.setBuddy(self.lineType)
        self.label_11.setBuddy(self.lineID)
        self.label_9.setBuddy(self.lineMode)
        self.label_10.setBuddy(self.lineAddress)
        self.label_3.setBuddy(self.lineDate)

        self.retranslateUi(QtSixAMainW)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.act_Exit, QtCore.SIGNAL(_fromUtf8("triggered()")), QtSixAMainW.close)
        QtCore.QMetaObject.connectSlotsByName(QtSixAMainW)

    def retranslateUi(self, QtSixAMainW):
        __sortingEnabled = self.listOfDevices.isSortingEnabled()
        self.listOfDevices.setSortingEnabled(False)
        item = self.listOfDevices.item(0)
        self.listOfDevices.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.devices), QtGui.QApplication.translate("QtSixAMainW", "Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.game_profiles), QtGui.QApplication.translate("QtSixAMainW", "Game Profiles", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.advanced), QtGui.QApplication.translate("QtSixAMainW", "Advanced", None, QtGui.QApplication.UnicodeUTF8))

import qtsixa_rc
